### ISSUE TITLE
Ceph issues on Ubuntu.

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#112]
This is a hunch that the issue is with Ubuntu after debugging with @xukan.

Tried running @xukan's ceph test cases and the test_get_image crashed due to
``` AttributeError: 'rbd.Image' object has no attribute 'name' ```

This is not happening on @xukan's server which is RHEL, but is happening in my Docker container which is Ubuntu.

The other weird difference we found is ubuntu doesnt need python-cephlibs whereas RHEL needs it. Installed python-cephlibs and got same issue.

My guess is that it is using some other rbd instead of python-cephlib's rbd.
P.S. We tried most of the uninstalling and reinstalling stuff.

@CCI-MOC/bmi-breakers ???

**Comment by chemistry-sourabh** [comment]
Ok update. ceps-common installed python-rbd that installed a rbd Shared Object in dist-packages. Did an rbd.__file__ in python and got the location of the shared object.

**Comment by chemistry-sourabh** [comment]
Ok fixed the issue on NEU VM. Now no need to install python-cephlibs as python-rbd and python-rados are enough. @xukan couldn't run your test case as there is an issue with ceph, but tested in python interpreter by importing rbd and rados and it worked. @xukan @naved001 I'll give the bad news now, the reason I was having ceph issues is because /etc/ceph/ceph.conf is missing!! That file is needed to fix it, You guys can try scping from 127.

**Comment by chemistry-sourabh** [comment]
Ok I doubt it will work as ubuntu just installs the shared object where as RHEL installs python-cephlibs also along with python-rbd and python-rados which screws up consistency, why RH why!!

**Comment by naved001** [comment]
I am gonna close this issue because:

* the install script has the right methods to install ceph (thanks @djfinn14 and @sirushtim )
* this is more like a ceph installation problem than BMI itself.
