### ISSUE TITLE
Setup CI on Travis

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#117]
Going to create an all in Docker image based on #93 .
This image will be based from ceph and install HIL and BMI into the container. Then will modify travis to build this container and execute test cases.

Only two questions
@naved001 can HIL be installed in ubuntu ?
Again @naved001 how do I test the travis thing ? Asking since you did the pep8

**Comment by chemistry-sourabh** [comment]
Update to this issue. 
Couldn't create an all in one image and instead created CI with 3 containers. Also this issue adds Code Coverage Measurement in CI. We will be using Coveralls for this as it is free for open source projects and seems to be popular.

**Comment by naved001** [comment]
#119 takes care of this.
