### ISSUE TITLE
BMI-Dev inaccessible via root

### ISSUE THREAD

**Issue by pgrosu** [CCI-MOC/ims#123]
I am trying to log into bmi-dev on neu-haas to run certain tests and I cannot get into it anymore.  Has the root password changed?

Thanks,
Paul

**Comment by chemistry-sourabh** [comment]
Please don't create issues related to internal infrastructure stuff. Ask on slack instead

**Comment by pgrosu** [comment]
Had to, didn't get the response in time - closing it.
