### ISSUE TITLE
Einstein server starts 3 processes

### ISSUE THREAD

**Issue by pgrosu** [CCI-MOC/ims#124]
When the einstein server gets started, is it supposed to be 3 separate processes?  The picasso server is only one process.

**Comment by apoorvemohan** [comment]
If you have any questions ask on slack, please do not create issues for such questions.

**Comment by pgrosu** [comment]
These discussions are fairly common on Github, and we need to start having them here, rather than on Slack where the reasoning might get lost.  For now, sure we can have a smooth transition, plus I think I figured it out.  We definitely need to begin documenting these publicly with the reasoning behind them.  Then we can use the documentation as provenance in conjunction with these discussions as references for the next version, as well pointing new users to our progressive approach.

**Comment by chemistry-sourabh** [comment]
To your answer. 1 is the name server, 1 the rpc server and the other one is the main process that starts both.

**Comment by pgrosu** [comment]
Thanks @chemistry-sourabh!

**Comment by apoorvemohan** [comment]
>These discussions are fairly common on Github, and we need to start having them here, rather than on Slack where the reasoning might get lost. For now, sure we can have a smooth transition, plus I think I figured it out. We definitely need to begin documenting these publicly with the reasoning behind them. Then we can use the documentation as provenance in conjunction with these discussions as references for the next version, as well pointing new users to our progressive approach.

- Discussions regarding issues and new features should/must be done on Github as automatically maintains creates a reference point for future. However, Github is not a place clarify general doubts. 
- We all acknowledge that we lack sufficient documentation and we need to improve it. (0.5-release is "a" stable version with bug-free basic functionalities that is meant to be used by internal teams or  and not for public release). The version that will be made public should have a good documentation.
- Implementation-decision specific details are documented as comments in the code as a reference for future and to help other developers understand the code (e.g. docstring for python).
