### ISSUE TITLE
Requests from Secure Cloud

### ISSUE THREAD

**Issue by djfinn14** [CCI-MOC/ims#129]
The Secure Cloud team has asked for changes in BMI to help them complete the paper they need completed by end of August. There are 3 different requests (listed below), and after meeting with them we were planning on developing them in a separate branch from dev, but I believe with the intention of eventually merging them when they are better polished. Looking for input from the team if you have concerns, advice, etc.:

1.     An API call to run a script on an Image, and returning the STDOUT, STDERR and return code.
2.     An API call that returns the iSCSI target information on a provisioned node.
3.     Separating out HIL calls from BMI.

**Comment by chemistry-sourabh** [comment]
@djfinn14 we need more specifics here. 
1. How should the script be run in the script ? ssh ? Do they want it to run earlier ?
2. more specificity on what iSCSI related information is required.
3. Is it similar to what @apoorvemohan suggested in the plans ? Make HIL and BMI independent ?

**Comment by djfinn14** [comment]
1. From my understanding, they want a bash script file in their local directory, then run a command such as bmi run_script IMAGE_NAME SCRIPT_NAME. BMI should rbd map the image, give the  device location to the script, and then let the script run on that image to obtain information like kernel/initrd/command line. Then BMI will rbd unmount. They are the ones writing the script to perform what they need.

2. This is an example we came up with them for what they want returned:
           {
             "iscsi_target": "iscsi:192.168.29.23:tcp:3260:1:5img7"          
           }

3. Yes I believe so; their allocation script is managing the networks in a very particular way and therefore they are looking to remove HIL functionality from BMI.

Again, for the immediate future this would be a separate branch. Also, I was asked to take point on this, so I would be the one coding it up, just wanted to make sure people are aware of this if they have input.

**Comment by chemistry-sourabh** [comment]
I am fine with 2 and 3, but regarding 1, I thought that the script will run on an already provisioned node.

Also maintain your new branch in such a way that you can raise 3 PRs when it is time to merge to master/dev (maintaining a commit for each task should be good).

**Comment by ravisantoshgudimetla** [comment]
> From my understanding, they want a bash script file in their local directory, then run a command such as bmi run_script IMAGE_NAME SCRIPT_NAME. BMI should rbd map the image, give the device location to the script, and then let the script run on that image to obtain information like kernel/initrd/command line. Then BMI will rbd unmount. They are the ones writing the script to perform what they need.

If you can find the exact information needed, instead of mounting the image and querying the information, we can do it once, store the metadata in DB. Probably import _mage API could have this image inspection feature. This could be part of higher list_image API call. WDYT?

2 is also possible and could be integrated into list_image API call again.

3 is something that I am not sure of. Can you provide some more information on it?

**Comment by djfinn14** [comment]
Here is what @henn had sent us regarding what they were looking for from BMI, not sure if he has additional comments for @ravisantoshgudimetla 's questions above. I have also attached the spec of the APIs that were discussed:

BMI

Needs an API to fetch kernel/initrd/command line from a Linux image. Must modify the kernel command line to incorporate the iSCSI target. As discussed with the team, needs to be quick and dirty:
mount the image to a known location
Run a custom script
umount the image.
These steps give us a natural evolution for running user code. Today, we'll use ceph's "rbd mount", but in the future BMI could mount it through a disposable VM/container through the iSCSI interface to be more secure.
Must modify the kernel command line to incorporate the iSCSI target.
Need to separate HIL calls from BMI calls, since the allocation script is managing the networks in a very particular way
Need API to get the iSCSI server
We need a BMI API server in PRB.
Not sure if this means installing a new one or recycling the one that's there


[Secure Cloud API Specs.pdf](https://github.com/CCI-MOC/ims/files/1130979/Secure.Cloud.API.Specs.pdf)

**Comment by djfinn14** [comment]
Now that we are getting closer to all of these requests getting into the Secure Cloud branch of BMI, I wanted to see what people's reservations were on getting these into the main branch (after any changes people want and after tests are written for them). I know that @henn has stated multiple times that he hoped the functionality of these requests would make its way into the code base and  judging by the last comment on  #139 by @ravisantoshgudimetla it seems that not everyone agrees that they should make it to the main branch. Hoping to have a discussion of people's viewpoints on the matter.

**Comment by ravisantoshgudimetla** [comment]
@djfinn14 I am not against the feature as such, infact it is really useful. I am concerned about the implementation. If you look at my previous comments, I was suggesting another way to implement exposing the information rather getting the information from file. We need a concrete way to do these things as they define the state of system. If we decide to choose file, it should be source of truth always for everything or if we decide DB, it should be the source of truth for everything, that is my only concern.

**Comment by naved001** [comment]
@apoorvemohan @djfinn14 The secure cloud requests are now merged into the sec-cloud branch. Is there any reason to keep this open?

**Comment by naved001** [comment]
since nobody responded to my last comment; imma close this one too.
