### ISSUE TITLE
Defining a project in BMI

### ISSUE THREAD

**Issue by pgrosu** [CCI-MOC/ims#138]
In HIL a project [is defined as](http://hil.readthedocs.io/en/latest/rest_api.html#api-reference):

> project - a grouping of resources (e.g., headnodes, nodes, networks).

In OpenStack a project [is defined as](https://docs.openstack.org/mitaka/install-guide-obs/common/glossary.html#term-project):

> Projects represent the base unit of “ownership” in OpenStack, in that all resources in OpenStack should be owned by a specific project. In OpenStack Identity, a project must be owned by a specific domain.

What is a project in BMI and what are its properties?

Thanks,
Paul

**Comment by chemistry-sourabh** [comment]
@apoorvemohan

**Comment by ravisantoshgudimetla** [comment]
A project in our case is same the HIL or OpenStack(except for resources it manages),

 It is grouping of our resources like image, provisioned nodes information(like VLAN associated, name of node) etc.

**Comment by naved001** [comment]
@pgrosu if you are happy with the answer then please close this issue.

**Comment by naved001** [comment]
I am gonna close this issue. Please reopen if you want to discuss this further. @pgrosu
