### ISSUE TITLE
Ansible vs Shell Script for BMI Install

### ISSUE THREAD

**Issue by djfinn14** [CCI-MOC/ims#145]
We are looking to write a script to install a BMI production environment when we already have HIL and Ceph deployed. In the early discussion of this, @naved001 brought up the option of writing it as an Ansible script instead of a shell script, especially if it has a good way of rolling back what the script did incase it fails. I have done a few hours of research on the benefits of Ansible over Shell Scripts and have found that Ansible has a block/rescue format that might be able to be used for rolling back on failure. It also has "idempotency" which means the result of performing it once is exactly the same as the result of performing it repeatedly (good for things like mkdir). There also things like breaking your script into tasks so you can easily see what fails, etc.

The major benefit of using a shell script would be that we can re-use parts from #60 . I am looking to see if others have had more experience with Ansible and what their thoughts are on which would be the better choice.

**Comment by naved001** [comment]
closing this because we are doing ansible now #153
