### ISSUE TITLE
New ceph-deploy version breaks current dev install scripts

### ISSUE THREAD

**Issue by djfinn14** [CCI-MOC/ims#159]
With the new ceph-deploy 2.0.0, they removed the options of both ceph-deploy osd prepare and ceph-deploy osd activate. This causes intall_ceph.sh to fail. We need to either install ceph-deploy 1.5.39 instead or modify the script to use ceph-deploy osd create. Quick fix for people who want to use the scripts right now is to change the lines in install_packages.sh "sudo pip install -U ceph-deploy" to be "sudo pip install -U ceph-deploy==1.5.39"

**Comment by radonm** [comment]
Osd create looks better option.

Ancient software versions generally cause trouble.
