### ISSUE TITLE
Get rid of calls to attach and remove networks to hil (in this version of BMI).

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#162]
This came up after running HIL/BMI in kumo for a while. 

When user give up their nodes (or we take it forcibly from them), we don't want to deprovision the nodes because that will delete their image, so we just disconnect all the networks and remove it from their project (and with a script, delete the iPXE file).

 Now if a user wants to deprovision a node, they must add that node back to their project, connect the hil_network and only then they can call the `bmi dpro` command.

**Comment by Izhmash** [comment]
I'll work on this
