### ISSUE TITLE
Pep8 tests!

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#25]
We should setup Travis CI for tests. And to get the ball rolling, I'll start by adding pep8 tests since we are adding a lot of new code, so I think it's important to make sure that our code is clean and compliant. If you have any other suggestions for doing pep8, we can discuss that!

**Comment by chemistry-sourabh** [comment]
Solved add a resolved label

**Comment by chemistry-sourabh** [comment]
and close it as I can't

**Comment by naved001** [comment]
#26 solves this. there's no resolved label :(
