### ISSUE TITLE
TGT

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#29]
Currently we have a working TGT Driver, but we need to
1. Change subprocess to sh or atleast a wrapper as there is a lot of duplicate code.
2. If are sticking with subprocess remove all the shell=True.
3. Use sudo without password which will require the user or installer to create a new user with NOPASSWD sudo access. This user will have the permissions to all the files required by bmi.

**Comment by chemistry-sourabh** [comment]
I am thinking of writing a wrapper for subprocess instead of using sh as sh doesn't use subprocess anymore. And as Ravi mentioned in previous PR subprocess is officially supported

**Comment by chemistry-sourabh** [comment]
PR is merged

**Comment by naved001** [comment]
After discussion with @apoorvemohan  we decided to keep it merged.
