### ISSUE TITLE
ISCSI Mock

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#32]
Need to write a Mock Driver for ISCSI that extends the ISCSI interface. This driver should have a sqlite db so that it can store persistent targets like a real ISCSI server. This allows for unit tests to be written.

**Comment by chemistry-sourabh** [comment]
@ravisantoshgudimetla in the setup phase of the testcase I guess the developer is supposed to set the target_list and run the test case right ? This will remove the need for any persistant storage ?

**Comment by ravisantoshgudimetla** [comment]
Right, just leave the person who is writing the test case to set them. That should be good enough. No need to use file validation 👍

**Comment by ravisantoshgudimetla** [comment]
@chemistry-sourabh , I am not sure, if you understood this correctly. Most of the integration tests that we wrote will be unit tests for corresponding systems. operations.py unit tests have to be split across various systems and these mocks will be used for integration tests.

**Comment by chemistry-sourabh** [comment]
I got it

**Comment by chemistry-sourabh** [comment]
Closing this since the PR is merged
