### ISSUE TITLE
Using HIL to attach and detach network

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#40]
Currently, we make an API call to HIL to attach and detach the provisioning network. 

https://github.com/CCI-MOC/ims/blob/dev/ims/einstein/operations.py#L210

This makes BMI dependent on HIL to do that. Should we not be doing this from HIL manually (or any other HIL like service), and keep BMI independent of it?

@ravisantoshgudimetla @apoorvemohan What are your thoughts on this?

**Comment by ravisantoshgudimetla** [comment]
Ok, I am back. The provision and deprovision calls are the ones where we are making HIL calls. We have to depend on some network isolation tool to achieve that. It may not be HIL as such it can be replaced with ironic or anything. So, in short, we have to use some code that is used for network isolation. Unless we move provision and deprovision calls out of BMI, I think there is no way to take them out.

**Comment by chemistry-sourabh** [comment]
I remember that you had a discussion with Orran that the user should use BMI to just mount an image on iscsi and use HIL to connect to network and reboot.

I was thinking of removing the HIL call in provision and deprovision and write a separate command that calls provision and connect to network (same for dpro). Also another command can be added that will also additionally reboot the node.

**Comment by naved001** [comment]
@ravisantoshgudimetla 

> We have to depend on some network isolation tool to achieve that. It may not be HIL as such it can be replaced with ironic or anything.

We need to use some network isolation tool and right now we have hard coded it to be HIL. Should we make network isolation tool a plug-in then, so that we could use ironic or anything then? Or are we okay with it being just HIL at the moment. 

@chemistry-sourabh Do you want to reboot the node by making a call to HIL (because HIL has all the OBM drivers/credentials to do so)? That would be pretty convenient, but again that means relying on HIL.

**Comment by chemistry-sourabh** [comment]
Ya, it will be a requirement for the network isolator that it should be able to reboot nodes. @ravisantoshgudimetla I am not sure as ironic can be used as it is equal to BMI. @sirushtim can you clarify this ?

**Comment by ravisantoshgudimetla** [comment]
@naved001 - once we have an interface defining contract, its identical to plugin based architecture. Let me know, if you have something else in your mind. 
@chemistry-sourabh - Ironic can reboot the nodes as well. The problem with ironic is it tries to do lot of stuff. Something like network isolation and provisioning engine should be separate. If we combine both it will be a problem. This a some tool like MaaS and Ironic can use same tool and later could be used for provisioning.(Its similar to microservices  where service is replaced by a component). Let me know, if you still have questions.

**Comment by chemistry-sourabh** [comment]
@ravisantoshgudimetla  you didn't comment on the initial comment I made on adding additional commands.

**Comment by ravisantoshgudimetla** [comment]
> I remember that you had a discussion with Orran that the user should use BMI to just mount an image on iscsi and use HIL to connect to network and reboot.

Provision is the call that is supposed to all of this. The user need not know that we are attaching a node to that network using or HIL or some other network isolation tool. So, we shouldn't separate them.

> I was thinking of removing the HIL call in provision and deprovision and write a separate command that calls provision and connect to network (same for dpro). Also another command can be added that will also additionally reboot the node.

If you create something like that, we are in fact proxying HIL's calls, which probably is not correct. HIL should do that.

**Comment by chemistry-sourabh** [comment]
@ravisantoshgudimetla I think you didnt get me here.
I meant provision will only only do the iscsi mounting and separate call will connect to HIL and call provision. Just an additional layer of flexibility as some users may prefer to directly use network isolator ( Probably because we dont support it ).

**Comment by ravisantoshgudimetla** [comment]
@chemistry-sourabh , I didn't get you even now. Let me know, if you want to have a call to discuss this.

**Comment by chemistry-sourabh** [comment]
Ok Let me try this way.
Right now if you do a bmi pro it will mount a clone and connect the node using HIL.
This is what I am proposing.
bmi pro will just mount the clone
bmi pro -c will also connect the node using HIL
bmi pro -r will mount the clone and reboot ( will need to use -c to work properly though)

Does it make sense now ?

**Comment by ravisantoshgudimetla** [comment]
Ok, I get what you are trying to do now and thats good. But provision is supposed to be a call that is supposed to do everything. I always think of provision as an atomic call and the advantage being not being abused. If we add an option to connect the node/ reboot the node using HIL and provide that as an option to user, he/she may use it for other systems. If you have proper validations to ensure that user will not be able to do that, then it makes sense for example, bmi pro -c(it cannot be used for attaching any node to network unless mounting the clone happens, which may not be case everytime), I am all in for those options.

**Comment by chemistry-sourabh** [comment]
That is not a huge issue

**Comment by ravisantoshgudimetla** [comment]
@chemistry-sourabh , I didn't understand, to me - its actually a big issue. In a way, we are proxying HIL again which is not what we want to do(HIL is supposed to do a node reboot not BMI).

**Comment by chemistry-sourabh** [comment]
HIL is supposed to do the node connect, but we are doing using HIL isn't that proxying ?

**Comment by ravisantoshgudimetla** [comment]
Nope, if we are exposing that service to user then it is proxying. Proxying from services perspective is different from user perspective.

**Comment by chemistry-sourabh** [comment]
So you are saying leave it as it is?

**Comment by naved001** [comment]
I am gonna close this because this is being discussed in several other BMI redesign threads/emails/snapchat-stories etc.
