### ISSUE TITLE
Strategy to promote from dev to master branch

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [CCI-MOC/ims#44]
@CCI-MOC/bmi-breakers : Once we merge the PR's into dev branch, we need to come up with some check list based on which we need to promote the code from dev to  master branch. Some of the items that we need to have:

- PEP 257(optional).
- Unit tests for all the functions written.
- Integration tests.

As of now, we have Travis CI(which is really good. Thanks @naved001)  but the idea is to use Openshift jenkins for integration tests(similar to Gates that we have for openstack). @akshayakhare has setup last semester. We need to integrate that. Please add in case you guys have anything else in mind.

**Comment by chemistry-sourabh** [comment]
@ravisantoshgudimetla I am not part of the bmi-breakers team. Not fair as I break it the most :P.
Also the confusion I am having is the test cases should run on the PR for the master branch right ?
Also the PR that is raised for master branch should go under code review ?
As per my understanding the PRs for dev branch will have a blind merge.
Also we can't promote anything until atleast the unit tests are written and the branch passes them.

**Comment by chemistry-sourabh** [comment]
@CCI-MOC/bmi-breakers nobody answered my confusion here

**Comment by naved001** [comment]
Just to clarify things, we won't be making **any** blind merges in the dev branch. Treat it like the master branch for all intents and purposes. Once we have unit and integrations tests for this, we'll make it the master branch and purge the current master. @apoorvemohan @sirushtim we on the same page here, yeah?

**Comment by chemistry-sourabh** [comment]
So we wont have a dev branch at all ?

**Comment by sirushtim** [comment]
@chemistry-sourabh IMO, we don't really need a dev branch. The PR's are effectively a dev branch.

Yeah, and what @naved001 mentioned is the consensus reached so far.

**Comment by ravisantoshgudimetla** [comment]
@CCI-MOC/bmi-breakers , I think we should have this branch as an alpha branch. All new development features should go in there and if sufficiently tested, should be merged in master.

>Just to clarify things, we won't be making any blind merges in the dev branch. Treat it like the master branch for all intents and purposes. Once we have unit and integrations tests for this, we'll make it the master branch and purge the current master.
I am against this - There may be a scenario eg ,for a research paper, we code something, we want to have it somewhere in this repo rather than in some user's branch.

**Comment by chemistry-sourabh** [comment]
My initial intuition of a dev branch is to have a single branch for everyones dev branches

**Comment by naved001** [comment]
We mostly have tests running in Travis now (although, coverage is still only 52%). 

And as @gc00 advised, we merged dev to master, and will continue from there.
