### ISSUE TITLE
Test Cases[Tracking issue]

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [CCI-MOC/ims#50]
I think @naved001 and @sirushtim have started working on some test cases. I just want to use this as a tracking issue. Please refer this issue other in other testing issues.

**Comment by chemistry-sourabh** [comment]
@naved001 and @sirushtim please review the crappy test cases that I wrote. I tried writing them in a way such that it will be easy to skip entire classes altogether.
Let me know if you guys know about any frameworks which allow us to do the same thing.

**Comment by ravisantoshgudimetla** [comment]
@naved001 and @sirushtim : Any update on this?

**Comment by naved001** [comment]
@chemistry-sourabh I have started looking at the tests now. It appears that the tests need some real hardware to work with (or I could be wrong). Can you briefly explain what kind of environment will the tests run in? I made a clone of the BMI VM on NEU cluster, there I tried to run the tests, but got all sorts of error. Thanks!

**Comment by chemistry-sourabh** [comment]
You will probably need to tweak the constants in the tests. Also you will need TGT to be running, along with ceph and HIL with a mock or real node. Bottom line a practical setup, but should run in the dev environment

**Comment by chemistry-sourabh** [comment]
This is what I am thinking. After @sirushtim's script is done we can fix the existing test cases and add them to Travis. Travis will use the script to setup the dev environment and run the test cases.
Any thoughts ?

**Comment by chemistry-sourabh** [comment]
@CCI-MOC/bmi-breakers review the test PRs first. If all of them are merged then you guys can get started.

**Comment by chemistry-sourabh** [comment]
Fixed Existing Test cases
Added Test docs
Added Test Cases for Config

**Comment by ravisantoshgudimetla** [comment]
@chemistry-sourabh Add PR's as xrefs here. Also, come up with list of items, even at high level, while assigning.

**Comment by naved001** [comment]
Closing this because, 
 * since most of the code that will be written will come with tests;
* and we did add some tests for the current codebase.
