### ISSUE TITLE
Change name HaaS to HIL everywhere in codebase

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [CCI-MOC/ims#51]
HIL naming has been changed in few places but missing in few places like:

https://github.com/CCI-MOC/ims/blob/dev/ims/einstein/operations.py#L264
and in files like https://github.com/CCI-MOC/ims/blob/dev/ims/exception/haas_exceptions.py
This may be a super mechanical task but will be a good starting point to new developers.

**Comment by xukan** [comment]
@ravisantoshgudimetla , hi, do we want to replace all haas naming with hil or just for exceptions like HaaSException ->HILException. For example,  we have some variables like haas_status_code, do we also want to change those names to hil_*?

**Comment by ravisantoshgudimetla** [comment]
@xukan , I guess we need to rename everything. Let me change the name for this issue.

**Comment by chemistry-sourabh** [comment]
Change all HaaS to HIL, but raise 2 PRs
