### ISSUE TITLE
Don't hardcode HAAS_BMI_CHANNEL

### ISSUE THREAD

**Issue by sirushtim** [CCI-MOC/ims#55]
To get a mock setup, we cannot hardcode the HAAS_BMI_CHANNEL in ims. Have a way to set HAAS_BMI_CHANNEL in the configuration file.

**Comment by chemistry-sourabh** [comment]
+1 faced the issue with mock hil

**Comment by ravisantoshgudimetla** [comment]
Am I missing anything here. This value has to be always vlan/native. Any reason, why we are hitting this bug with mock hil?

**Comment by chemistry-sourabh** [comment]
No clue. For some reason the mock network only has a null channel. So BMI doesn't work out of the box. @naved001 did you find a fix for this ?

**Comment by sirushtim** [comment]
Doesn't it make sense for a mock network to only have a null channel? because a mock network can't do vlan/native and that's why the HaaS API rejects that request.

**Comment by ravisantoshgudimetla** [comment]
I think, if we configure this as a parameter, people may again abuse it, for example trying to boot it off vlan/100 etc, which is not going to work. So, it shouldn't configurable I think.

**Comment by chemistry-sourabh** [comment]
We dont have vlan/native for dev environment, Any ideas on that ? It will be removed from the central constants and put into the driver, but we still need the null channel.

Or when we make it a driver we can add some dev mode which will allow us to use the null channel ?

**Comment by ravisantoshgudimetla** [comment]
>We dont have vlan/native for dev environment

I didn't follow you. If you are thinking how to make it work for integration tests, we can mock it as well. In HIL section, it should have a parameter called channel should have two values, either mock or production, if its production it will be vlan/native, if its mock, it will be either mock or someother value. This will be part of HIL driver code.

**Comment by chemistry-sourabh** [comment]
the mock driver only gives you null channel. But anyways you gave the solution which I was talking about so I am fine with that

**Comment by apoorvemohan** [comment]
@chemistry-sourabh can we close this?
