### ISSUE TITLE
Picasso API Startup Error

### ISSUE THREAD

**Issue by sirushtim** [CCI-MOC/ims#59]
ubuntu@test-bmi-1:~/ims$ python scripts/picasso_server
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file _internal.py, line 87

The port after being read from the config file needs to be casted to int before being used in app.run() in ims/picasso/rest.py

**Comment by chemistry-sourabh** [comment]
Are you sure ? this is related to logging. I didnt face any issues. Can you describe steps to reproduce and the config file you used ?

**Comment by chemistry-sourabh** [comment]
@sirushtim try reproducing this with the latest dev

**Comment by sirushtim** [comment]
@chemistry-sourabh Yes, changing the config to a declarative style certainly will fix this. Now you know why I was so persistent on it. :P
