### ISSUE TITLE
Documentation should be a part of the git repo

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#64]
The BMI setup instructions are a part of the MOC wiki so that everything about MOC can be reached from one page. 

In my opinion, we should have the installation instructions in the mainline repo *too* as a part of documentation (`/docs/Installation.md`). There we can add more stuff, like a separate document for setting up the dev environment(`/docs/Installation-developers.md`), (`/docs/developer-guidlines.md`), (`/docs/testing-bmi.md`) etc. So that whoever clones the repo will have the documents available offline. Any thoughts?

**Comment by chemistry-sourabh** [comment]
That and we can move the docs to the project wikis and put a link to the wikis in the MOC wiki. You can convert the docs to the way you did for HIL instead of putting it in wikis.

**Comment by naved001** [comment]
Yeah, I'll put the docs on readthedocs once we have those in the repo. That'd be neat. I'll wait to hear what others have to say, and then I'll add it.

**Comment by sirushtim** [comment]
Sounds good to me. :+1:

**Comment by chemistry-sourabh** [comment]
Better make a list of the docs that should be present.

**Comment by chemistry-sourabh** [comment]
@naved001 do we want to close this issue yet ? Did we finish adding all the required docs ?
