### ISSUE TITLE
Unit tests for config object

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [CCI-MOC/ims#69]
@chemistry-sourabh , I see that you merged #41 but can you raise a PR with unit tests? With out them, they cannot go to master branch(or whatever the plan is for master branch)?

**Comment by chemistry-sourabh** [comment]
We need to sort out the testing framework first. I am interested in something like one file which grabs all test cases  and runs them. I wrote code for something like that, but no response

**Comment by ravisantoshgudimetla** [comment]
I don't know if this is for some discussion but usually - it should be something like a single python file for every unit test available and wrap all up in a shell script or other python script. Thats how we can get started on working atleast. I am not sure, if you have some framework in mind for that. JUnit could be used but its an unnecessary mess at this point. Lets try to have something very simple. 

\cc @sirushtim @naved001 @apoorvemohan

**Comment by chemistry-sourabh** [comment]
I would ask you guys to review the framework what I wrote first before going forward. If that is fine then we can get the existing tests working with travis.

**Comment by sirushtim** [comment]
Just an update for those following this thread, I've updated https://github.com/CCI-MOC/ims/pull/85 with an approach for the unit tests for config files and https://github.com/CCI-MOC/ims/pull/83 for approach on the test framework being used itself. If there are other ideas, it'd be good to hear them before we merge these changes.

**Comment by chemistry-sourabh** [comment]
Merged PR
