### ISSUE TITLE
DNS Services

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#71]
I am not sure if this should be part of BMI or HIL.
Right now neither of the services offers a DNS Service, but I feel it will be great for a lot of applications if we support it as we are the ones with a DHCP Server.
Also there should be an option for the user to disable our DNS if the user wants to use his own.
@CCI-MOC/bmi-breakers discuss!!

**Comment by apoorvemohan** [comment]
Covered in the redesign
