### ISSUE TITLE
Image name issues when 2 BMI instances are sharing the same ceph pool

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#78]
Discovered this while setting up a clone BMI VM which uses the same ceph pool as the original BMI VM. So I cannot provision a node because the image name already exists due to the original VM. Is there a way to change this behavior?

**Comment by chemistry-sourabh** [comment]
Change the uid in the config file. It was specifically added to avoid collisions.
The image name is constructed as follows uid + "img" + id
