### ISSUE TITLE
Right way to delete targets

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#90]
I didn't do research, but have a hunch.
in tgt-admin there is a --offline along with --delete. Right now we are doing tgt-admin --force --delete to delete a target. Typically in lots of software using the force option is not advised, but we need it to remove targets that are being used. I was thinking what if we do a --offline before doing a --delete ? Probably could reduce or eliminate the issue where we sometimes can't remove a target.

@CCI-MOC/bmi-breakers

**Comment by apoorvemohan** [comment]
IIRC, there was some problem when using "--offline" and "--delete" by themself. That's why we went for "--force --delete"

**Comment by chemistry-sourabh** [comment]
I never used --offline, but if you used it and didnt work then ok. We used --force as --delete was not enough.

**Comment by naved001** [comment]
looks like using force is the only way with TGT otherwise we coulnd't reliably remove targets. ( @apoorvemohan is here with me)
