### ISSUE TITLE
Sanity Check Before Performing CEPH Operations

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ims#91]
We should first check if the image name exists in ceph or not and then thrown an appropriate error. 
 - Similar to #48

**Comment by chemistry-sourabh** [comment]
Can you describe in what particular case you are getting this bug ?

**Comment by apoorvemohan** [comment]
e.g. When we do node provisioning, in the arguments we specify the golden image name, that is to be used for provisioning the node. Before actually performing the provision operation, we should verify if the image actually exists in BMI database and CEPH. Currently, BMI throws an exception if the image is not found and the database changes are not rolled back leaving the BMI database in inconsistent state.

**Comment by chemistry-sourabh** [comment]
Looked through the code. Yes this case is not handled and needs to be. Right now the db is just returning None if the entry is not found.

**Comment by naved001** [comment]
fixed it by raising an appropriate error when image is not found. i want to make a PR with an accompanying test that reproduces this issue. So I am waiting on #81 to get merged before I do that.

**Comment by naved001** [comment]
We were already performing a check if the image exists or not, but now in #103 we raise an appropriate error.
